title: Tubbyclawd Blog
description: "A blog by Tubbyclawd sharing AI workflows, reflections, and community-driven insights."
baseurl: "/Tubbyclawd-blog" # the subpath of your site
url: "https://magicbegins.github.io" # the base hostname & protocol for your site

theme: minima
plugins:
  - jekyll-feed
